language: elixir
git:
  depth: 1000
cache:
  directories:
    - _build
    - deps
addons:
  apt:
    packages:
      - docker-ce

elixir:
  - 1.8.1
otp_release:
  - 21.2.5
notifications:
  slack:
    rooms:
      - secure: "LRTw3OmfAQqoXJgXkXTdNP5r+qrfZuKMstSjOwzpiDYOvBHMZFwaJNVY/Szz3CreXo8Fz2QNeG0y00oSyWOBiHx6xKXPslVdnaED0jK3zXBn+Io8ajAYblIoAw4mPFhb33m7vPH93z3RuubaJF9XJkwc+s3o5TcVyUrz2YUFT6QhJW9Mia7x+2+b0rv/9P0hfbLyY8Mdpq23H014l+WxFA4lKRbL+igxFD2H8hiXnor1oXRJ5lLYcIMjQujoNIddOEJd49T1Pmd+xb+1cegy+FC49YoTT1949hGqGm1AZMULMSSCQvHCIrDwJ2eQ6rkjHIcqJ6QR+9xolCwRwWlpqwfHU/Zyyjs5CjE3fuSmZ9Z5y8eZfGOmLJMF4w2E5KnMyuqLh+7vKbQQtykJfwKhPRu77jjcHcypSHCEoy1qXLFQ39rHhZqNAaVYe2epvFgYCxiS+l8ThfIpQNxu+sSC63JOwN78atB6qfFrIh2ab/48LgGCLEKJcbwAslF/vs//LWe09VAayDUXOsr7trC1qDDCAQC9dtXdlC4YlkFp8KbsLNAUaUt5ZbMSfozlBm0fZmEnvmFgEOmkb2mpmcdvPxJoZWY+xkLTFYPSFvt2hjWpIU3cSg46TZQ/KRDWu338cJn6zODLfdUZpyInmGkFieAulqxoKNHGlpbmabDOd8Q="
    on_success: always
env:
  global:
    - NO_ECTO_SETUP=true
    - MIX_ENV=test
    - DOCKER_NAMESPACE=edenlabllc
    - APPS='[{"app":"edr_api","chart":"edr-api","namespace":"edr","deployment":"edr-api","label":"edr-api"}]'
    #Docker env's
    - secure: "OGyA5DKG7X2YIfG9Arbj7u+9VjJ/hLvcPy7x7cVEtxa8eWbAaCGN1Q4BdluccOsMOWAhqtTDVy3CAhxcnyuvDMn3m5LksXyNDoe3USeWZOsN1QQVeJeNzs8aLSfyrwm1zkPTaCgwyc7+zMu7tpHnSgK2kiLj80D83a8GTE39+glICnHcJJ1cNHT/upliE4eUTQvEffeZU7qbdOaQTaLipdRyrSZVbwyHvDB9lhL8J5pfj8izSUb2cRxIIl7RoUda8hEAksWtYc9zdpXnuFtY53wIMaviUd/wclN13yQ+sqJXpjMu8fKv58RN0dMbugn1y0yZUjns4AEmKO7Qzo2DHR7MMBzWPIvddR5YJVKx4BtrHJXlT3ZY9gYwAnRpdK+AH7gsaWPxi1yPNYWKQZbnpeRaWsQF6XI/Lcyj5GtgoS1DWAXAWKBwhTiQPSVvkSxT6hlkoMgryweTidvJJrs8SNOrMQgIQnaCli1lYSyoRBk6Qj+noszJdo3nxlHPUrLXonDO2rcsQwKlEPt5rMZZfs5YgoSpO8bUBpYNzuAn7BYCicKLVZxUbCINjwYZ90aijF1ssgaB8eX45pRH5VG2Tltiyi2TfOG00xTSOD3bFdfPCs+d4fyhhjk4mCbuyAEvJDINMbb/7fLE5QGzG4ldXF4N6MGV9qN7ZIcK0o0WvZI="
    #Github token
    - secure: "JVjbNlDkFza2FA3owZagjlST/D31pooMpDA4WzxtFCMrwRk88o9g3eoiZBqjn1IuZExwCf7MALmHnIfoaIA8EKiI49fsf5Yxogsk3KF/DPmVoSvtbPWoK6kd5gt9YtwNM+Vk0cHNBRMFR1jtiQvE5uHrZwPKgEMjwIiSMHEUysWrKgBeqqmQOD7mLo+wxZxDUN42jJYo2RyeolKmK3ep+xwAo+bFoJg2NbY5EJstC1N/atCFxvNk0Ckgd9S6nZgD/4HDz4g7PrfaHg8UsF57+sulPLvsyvbKKjKL7ucIlohtx3FQk0jID5mr7lQRQesHLfeg6H51OvWl4k3oMCSja6X/DO9TluW/gsmVlX2BnRbtsgAu5t1nO/dai0GD3SaN/2+k/D0WWqT2dXP+RGYnb3bbkf/sk7gxvFEFn025CKw43M27Z4OjD8M5Uw5Zh+pf31WUUQ1g/5RJ9/sl7X4SN0OdnqazpcIEvIyfNN7gXFC10DII2HlagLSN44I/sL/oh75H0NwP1fcqi7YmZ3OErpJOHkw78CisrOugiE1d5IFigJsYkNtTtSLREwc5prV83MZ9r3J8GHtdbdYP9ErvzPO6VbvPDs5NB8XlknMD3PpicYi4ZoUe+QmbNMgrRjU1IQe6VyanhOJRlz//hGRCNaUX/ndyspFEKj+RISAvqkg="
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - sudo apt-get install jq

jobs:
  include:
    - stage: "test and build"
      name: "Run tests"
      script:
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1

    - stage: "test and build"
      name: "Build Docker containers. EDR API"
      env:
        - APPS='[{"app":"edr_api","chart":"edr-api","namespace":"edr","deployment":"edr-api","label":"edr-api"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_a2a85018fd7a_key -iv $encrypted_a2a85018fd7a_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
